<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Taiwo Adegbola">
<meta name="dcterms.date" content="2026-07-22">

<title>Urban–Rural Differences in Malaria Prevalence Among Children Under Five in Nigeria: Evidence from the 2023 Nigeria Demographic and Health Survey (NDHS)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="under_5_malaria_prevalence_diff_files/libs/clipboard/clipboard.min.js"></script>
<script src="under_5_malaria_prevalence_diff_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="under_5_malaria_prevalence_diff_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="under_5_malaria_prevalence_diff_files/libs/quarto-html/popper.min.js"></script>
<script src="under_5_malaria_prevalence_diff_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="under_5_malaria_prevalence_diff_files/libs/quarto-html/anchor.min.js"></script>
<link href="under_5_malaria_prevalence_diff_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="under_5_malaria_prevalence_diff_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="under_5_malaria_prevalence_diff_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="under_5_malaria_prevalence_diff_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="under_5_malaria_prevalence_diff_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Urban–Rural Differences in Malaria Prevalence Among Children Under Five in Nigeria: Evidence from the 2023 Nigeria Demographic and Health Survey (NDHS)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Taiwo Adegbola </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">1. Background</h2>
<p>Malaria remains one of the leading causes of morbidity and mortality among children under five in Nigeria, which carries the highest global malaria burden of any single country. Transmission intensity and risk factors for malaria infection differ substantially by residence type — rural areas typically have greater proximity to mosquito breeding sites, lower net (ITN) coverage, reduced access to health facilities, and different housing construction (less screening, more open eaves), while urban areas generally benefit from better infrastructure, drainage, and healthcare access, though rapid unplanned urbanization can create localized high-risk pockets.</p>
<p>Understanding whether malaria prevalence differs meaningfully between urban and rural children is central to Nigeria’s National Malaria Elimination Programme (NMEP) planning, as it directly informs where intervention resources — ITN distribution, indoor residual spraying (IRS), seasonal malaria chemoprevention (SMC) — should be prioritized. The <strong>2023 Nigeria Demographic and Health Survey (NDHS)</strong> provides nationally representative malaria testing data that allow this important epidemiologic question to be investigated.</p>
<p><strong>Problem Statement</strong></p>
<p>Although Nigeria continues to implement comprehensive malaria control programmes, disparities in malaria burden may persist between urban and rural populations. Identifying whether significant differences exist in malaria prevalence according to place of residence can help policymakers prioritize interventions, allocate resources efficiently, and strengthen malaria control strategies in high-risk communities.</p>
</section>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">2. Objective</h2>
<p>To determine whether malaria test positivity among children aged 6–59 months differs significantly by residence type (urban vs.&nbsp;rural), using nationally representative Nigeria Malaria Indicator Survey (MIS) 2021 data.</p>
</section>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">3. Research Question</h2>
<p>Is malaria test positivity among children aged 6–59 months significantly associated with place of residence (urban versus rural) in Nigeria?</p>
</section>
<section id="data-source" class="level2">
<h2 class="anchored" data-anchor-id="data-source">4. Data Source</h2>
<p><strong>Survey:</strong> Nigeria Malaria Indicator Survey (MIS) 2021 — DHS Program</p>
<p><strong>Datasets:</strong> <code>NGKR81DT</code> (Children’s Recode), <code>NGHR81DT</code> (Household Recode)</p>
<p><strong>Design:</strong> Nationally representative, stratified, multi-stage cluster sample survey</p>
<p><strong>Population:</strong> Children aged 6–59 months with a valid malaria test result (RDT and/or microscopy)</p>
</section>
<section id="study-design" class="level2">
<h2 class="anchored" data-anchor-id="study-design">5. Study Design</h2>
<p>Cross-sectional analysis of nationally representative survey data (Nigeria MIS 2021).</p>
<p><strong>Population:</strong> Children aged 6–59 months residing in surveyed households across Nigeria’s 36 states +FCT.</p>
<p><strong>Exposure:</strong> Type of residence: Urban, Rural</p>
<p><strong>Outcome:</strong> Malaria test result (positive/negative) — RDT and/or microscopy confirmed</p>
<p><strong>Categorical (binary)</strong></p>
</section>
<section id="statistical-method" class="level2">
<h2 class="anchored" data-anchor-id="statistical-method">6. Statistical Method</h2>
<p>Chi-square test of independence <em>(with a note on applying DHS sampling weights, given the complex survey design)</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at C:/Users/farinto.joseph/Documents/GitHub/epidemiology-portfolio</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>raw_mis2021 <span class="ot">&lt;-</span> rio<span class="sc">::</span><span class="fu">import</span>(<span class="fu">here</span>(<span class="st">"datasets/NGPR81FL.dta"</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#head(raw_mis2021)</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#names(raw_mis2021)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(raw_mis2021)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 70428   225</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#str(raw_mis2021)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co">#head(raw_mis2021)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>state_lookup <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">state_code =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">37</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">state_name =</span> <span class="fu">c</span>(<span class="st">"Sokoto"</span>,<span class="st">"Zamfara"</span>,<span class="st">"Katsina"</span>,<span class="st">"Jigawa"</span>,<span class="st">"Yobe"</span>,<span class="st">"Borno"</span>,<span class="st">"Adamawa"</span>, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Gombe"</span>,<span class="st">"Bauchi"</span>,<span class="st">"Kano"</span>,<span class="st">"Kaduna"</span>,<span class="st">"Kebbi"</span>,<span class="st">"Niger"</span>,<span class="st">"FCT"</span>,<span class="st">"Nasarawa"</span>,                  <span class="st">"Plateau"</span>,<span class="st">"Taraba"</span>,<span class="st">"Benue"</span>,<span class="st">"Kogi"</span>,<span class="st">"Kwara"</span>,<span class="st">"Oyo"</span>,<span class="st">"Osun"</span>,<span class="st">"Ekiti"</span>,                    <span class="st">"Ondo"</span>,<span class="st">"Edo"</span>,<span class="st">"Anambra"</span>,<span class="st">"Enugu"</span>,<span class="st">"Ebonyi"</span>,<span class="st">"Cross River"</span>,<span class="st">"Akwa Ibom"</span>,                  <span class="st">"Abia"</span>,<span class="st">"Imo"</span>,<span class="st">"Rivers"</span>,<span class="st">"Bayelsa"</span>,<span class="st">"Delta"</span>,<span class="st">"Lagos"</span>,<span class="st">"Ogun"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mis2021_cleaned <span class="ot">&lt;-</span> raw_mis2021 <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cluster =</span> hv021,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">strata =</span> hv023,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_weight =</span> hv005,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">state_code =</span> hv024,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">residence =</span> hv025,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> hv104,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_months =</span> hc1,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">malaria_result =</span> hml32</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(state_lookup, <span class="at">by =</span> <span class="st">"state_code"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="co">#head(mis2021_cleaned)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_labels</span>(mis2021_cleaned<span class="sc">$</span>state_name)      <span class="co"># State/Region</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Benue"       "FCT"         "Kogi"        "Kwara"       "Nasarawa"   
 [6] "Niger"       "Plateau"     "Adamawa"     "Bauchi"      "Borno"      
[11] "Gombe"       "Taraba"      "Yobe"        "Jigawa"      "Kaduna"     
[16] "Kano"        "Katsina"     "Kebbi"       "Sokoto"      "Zamfara"    
[21] "Abia"        "Anambra"     "Ebonyi"      "Enugu"       "Imo"        
[26] "Akwa Ibom"   "Bayelsa"     "Cross River" "Delta"       "Edo"        
[31] "Rivers"      "Ekiti"       "Lagos"       "Ogun"        "Ondo"       
[36] "Osun"        "Oyo"        </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_labels</span>(mis2021_cleaned<span class="sc">$</span>residence)       <span class="co"># Residence</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "urban" "rural"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_labels</span>(mis2021_cleaned<span class="sc">$</span>sex)             <span class="co"># Sex</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "male"   "female"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_labels</span>(mis2021_cleaned<span class="sc">$</span>malaria_result)  <span class="co"># Malaria microscopy result</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "negative"                         "positive"                        
[3] "test undetermined"                "sample not found in lab database"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_labels</span>(mis2021_cleaned<span class="sc">$</span>strata)          <span class="co"># Strata</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "abia_urban"        "abia_rural"        "adamawa_urban"    
 [4] "adamawa_rural"     "akwa ibom_urban"   "akwa ibom_rural"  
 [7] "anambra_urban"     "anambra_rural"     "bauchi_urban"     
[10] "bauchi_rural"      "bayelsa_urban"     "bayelsa_rural"    
[13] "benue_urban"       "benue_rural"       "borno_urban"      
[16] "borno_rural"       "cross river_urban" "cross river_rural"
[19] "delta_urban"       "delta_rural"       "ebonyi_urban"     
[22] "ebonyi_rural"      "edo_urban"         "edo_rural"        
[25] "ekiti_urban"       "ekiti_rural"       "enugu_urban"      
[28] "enugu_rural"       "fct_urban"         "fct_rural"        
[31] "gombe_urban"       "gombe_rural"       "imo_urban"        
[34] "imo_rural"         "jigawa_urban"      "jigawa_rural"     
[37] "kaduna_urban"      "kaduna_rural"      "kano_urban"       
[40] "kano_rural"        "katsina_urban"     "katsina_rural"    
[43] "kebbi_urban"       "kebbi_rural"       "kogi_urban"       
[46] "kogi_rural"        "kwara_urban"       "kwara_rural"      
[49] "lagos_urban"       "lagos_rural"       "nasarawa_urban"   
[52] "nasarawa_rural"    "niger_urban"       "niger_rural"      
[55] "ogun_urban"        "ogun_rural"        "ondo_urban"       
[58] "ondo_rural"        "osun_urban"        "osun_rural"       
[61] "oyo_urban"         "oyo_rural"         "plateau_urban"    
[64] "plateau_rural"     "rivers_urban"      "rivers_urban"     
[67] "rivers_rural"      "rivers_rural"      "sokoto_urban"     
[70] "sokoto_rural"      "taraba_urban"      "taraba_rural"     
[73] "yobe_urban"        "yobe_rural"        "zamfara_urban"    
[76] "zamfara_rural"    </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">table</span>(mis2021_cleaned<span class="sc">$</span>malaria_result, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1  &lt;NA&gt; 
 8390  2265 59773 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mis2021_final <span class="ot">&lt;-</span> mis2021_cleaned <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age_months <span class="sc">&gt;=</span> <span class="dv">6</span>, age_months <span class="sc">&lt;=</span> <span class="dv">59</span>, <span class="sc">!</span><span class="fu">is.na</span>(malaria_result)) <span class="sc">|&gt;</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_weight =</span> sample_weight <span class="sc">/</span> <span class="dv">1000000</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">malaria_status =</span> <span class="fu">factor</span>(malaria_result, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Negative"</span>,<span class="st">"Positive"</span>)),</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">residence_cat =</span> <span class="fu">factor</span>(residence, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Urban"</span>,<span class="st">"Rural"</span>)),</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex_cat =</span> <span class="fu">factor</span>(sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Male"</span>,<span class="st">"Female"</span>))</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mis2021_final)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10655</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mis2021_final)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  cluster strata sample_weight state_code residence sex age_months
1       1     13      1.119345         18         1   2         57
2       1     13      1.119345         18         1   1         44
3       1     13      1.119345         18         1   1         18
4       1     13      1.119345         18         1   1         43
5       1     13      1.119345         18         1   1         38
6       1     13      1.119345         18         1   2         19
  malaria_result state_name malaria_status residence_cat sex_cat
1              0      Benue       Negative         Urban  Female
2              0      Benue       Negative         Urban    Male
3              0      Benue       Negative         Urban    Male
4              0      Benue       Negative         Urban    Male
5              0      Benue       Negative         Urban    Male
6              1      Benue       Positive         Urban  Female</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(mis2021_final)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 10,655
Columns: 12
$ cluster        &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ strata         &lt;dbl&gt; 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,…
$ sample_weight  &lt;dbl&gt; 1.119345, 1.119345, 1.119345, 1.119345, 1.119345, 1.119…
$ state_code     &lt;dbl&gt; 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,…
$ residence      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ sex            &lt;dbl&gt; 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1…
$ age_months     &lt;dbl&gt; 57, 44, 18, 43, 38, 19, 28, 49, 42, 19, 54, 43, 23, 37,…
$ malaria_result &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0…
$ state_name     &lt;chr&gt; "Benue", "Benue", "Benue", "Benue", "Benue", "Benue", "…
$ malaria_status &lt;fct&gt; Negative, Negative, Negative, Negative, Negative, Posit…
$ residence_cat  &lt;fct&gt; Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban,…
$ sex_cat        &lt;fct&gt; Female, Male, Male, Male, Male, Female, Female, Male, M…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(mis2021_final))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       cluster         strata  sample_weight     state_code      residence 
             0              0              0              0              0 
           sex     age_months malaria_result     state_name malaria_status 
             0              0              0              0              0 
 residence_cat        sex_cat 
             0              0 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mis2021_final<span class="sc">$</span>residence)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2 
3100 7555 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mis2021_final<span class="sc">$</span>sex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2 
5470 5185 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mis2021_final<span class="sc">$</span>malaria_status)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Negative Positive 
    8390     2265 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'survey' was built under R version 4.6.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: grid</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'survey'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:graphics':

    dotchart</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>mis_design <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">ids =</span> <span class="sc">~</span>cluster,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">strata =</span> <span class="sc">~</span>strata,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="sc">~</span>sample_weight,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> mis2021_final</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mis_design)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stratified 1 - level Cluster Sampling design (with replacement)
With (567) clusters.
svydesign(ids = ~cluster, strata = ~strata, weights = ~sample_weight, 
    data = mis2021_final)
Probabilities:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.2585  0.7503  1.1520  1.5390  1.6764 39.6825 
Stratum Sizes: 
            1   2  3   4  5   6  7   8  9  10 11  12 13  14  15 16 17  18  19
obs        64 167 66 195 21 134 49 145 74 342 57 188 65 252 270 73 36 201 134
design.PSU  3  11  4  11  2  13  4  12  3  13  4   9  4  12  12  4  3  12   7
actual.PSU  3  11  4  11  2  13  4  12  3  13  4   9  4  12  12  4  3  12   7
            20 21  22 23 24 25 26 27  28  29  30 31  32 33  34 35  36  37  38
obs        213 44 257 32 73 56 94 85 138 117 126 71 188 32 164 39 359 129 295
design.PSU   9  2  11  5 10  5  9  6   9   8   4  4  10  2  14  2  14   5  12
actual.PSU   9  2  11  5 10  5  9  6   9   8   4  4  10  2  14  2  14   5  12
           39  40 41  42 43  44 45  46 47  48  49 50  51  52  53  54 55 56  57
obs        81 440 76 372 65 330 45 159 65 105 109 71 111 341 100 263 86 86 154
design.PSU  5  13  4  13  3  12  4  11  6   8  12  6   4   9   4  12  7  8  12
actual.PSU  5  13  4  13  3  12  4  11  6   8  12  6   4   9   4  12  7  8  12
           58  59 60  61 62 63  64  65 66  67 68 69  70 71  72 73  74 75  76
obs        57 101 47 120 59 99 226 129 45 132 43 80 293 76 312 62 310 55 305
design.PSU  3   9  6  11  4  5  10   8  4   9  4  3  12  3  11  3  11  3  11
actual.PSU  3   9  6  11  4  5  10   8  4   9  4  3  12  3  11  3  11  3  11
Data variables:
 [1] "cluster"        "strata"         "sample_weight"  "state_code"    
 [5] "residence"      "sex"            "age_months"     "malaria_result"
 [9] "state_name"     "malaria_status" "residence_cat"  "sex_cat"       </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>malaria_status, mis_design)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          mean     SE
malaria_statusNegative 0.77733 0.0096
malaria_statusPositive 0.22267 0.0096</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>( <span class="sc">~</span>malaria_status, <span class="sc">~</span>residence_cat, mis_design, svymean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      residence_cat malaria_statusNegative malaria_statusPositive
Urban         Urban              0.8952417              0.1047583
Rural         Rural              0.7333433              0.2666567
      se.malaria_statusNegative se.malaria_statusPositive
Urban                0.01055976                0.01055976
Rural                0.01187408                0.01187408</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>( <span class="sc">~</span>malaria_status, <span class="sc">~</span>sex_cat, mis_design, svymean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       sex_cat malaria_statusNegative malaria_statusPositive
Male      Male              0.7770025              0.2229975
Female  Female              0.7776674              0.2223326
       se.malaria_statusNegative se.malaria_statusPositive
Male                  0.01130364                0.01130364
Female                0.01038325                0.01038325</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svytable</span>(<span class="sc">~</span>residence_cat <span class="sc">+</span> malaria_status, <span class="at">design =</span> mis_design)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             malaria_status
residence_cat  Negative  Positive
        Urban 2690.0419  314.7801
        Rural 5907.6406 2148.1230</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">svytable</span>(<span class="sc">~</span>residence_cat <span class="sc">+</span> malaria_status, <span class="at">design =</span> mis_design), <span class="at">margin =</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             malaria_status
residence_cat Negative Positive
        Urban 89.52417 10.47583
        Rural 73.33433 26.66567</code></pre>
</div>
</div>
<section id="statistical-hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="statistical-hypotheses">Statistical Hypotheses</h3>
<p><strong>Null Hypothesis (H₀):</strong></p>
<p>There is <strong>no association</strong> between place of residence (urban/rural) and malaria infection among children aged 6–59 months in Nigeria.</p>
<p><strong>Alternative Hypothesis (H₁):</strong></p>
<p>There <strong>is an association</strong> between place of residence (urban/rural) and malaria infection among children aged 6–59 months in Nigeria.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svychisq</span>(<span class="sc">~</span>residence_cat <span class="sc">+</span> malaria_status, <span class="at">design =</span> mis_design)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's X^2: Rao &amp; Scott adjustment

data:  svychisq(~residence_cat + malaria_status, design = mis_design)
F = 84.716, ndf = 1, ddf = 491, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svyciprop</span>(<span class="sc">~</span><span class="fu">I</span>(malaria_status <span class="sc">==</span> <span class="st">"Positive"</span>), </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">design =</span> <span class="fu">subset</span>(mis_design, residence_cat <span class="sc">==</span> <span class="st">"Urban"</span>), </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">method =</span> <span class="st">"logit"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         2.5%  97.5%
I(malaria_status == "Positive") 0.1048 0.0857 0.1275</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svyciprop</span>(<span class="sc">~</span><span class="fu">I</span>(malaria_status <span class="sc">==</span> <span class="st">"Positive"</span>), </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">design =</span> <span class="fu">subset</span>(mis_design, residence_cat <span class="sc">==</span> <span class="st">"Rural"</span>), </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">method =</span> <span class="st">"logit"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                       2.5% 97.5%
I(malaria_status == "Positive") 0.267 0.244 0.291</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>weighted_props <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prop.table</span>(<span class="fu">svytable</span>(<span class="sc">~</span>residence_cat <span class="sc">+</span> malaria_status, <span class="at">design =</span> mis_design), <span class="at">margin =</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(weighted_props, <span class="fu">aes</span>(<span class="at">x =</span> residence_cat, <span class="at">y =</span> Freq, <span class="at">fill =</span> malaria_status)) <span class="sc">+</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Weighted Malaria Test Result by Residence"</span>,</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Nationally representative estimates (Nigeria MIS 2021)"</span>,</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Residence"</span>,</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion"</span>,</span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Malaria Result"</span></span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="under_5_malaria_prevalence_diff_files/figure-html/visualize-%20stacked_bar_malaria-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">7. Interpretation</h2>
<p>A Rao–Scott adjusted Chi-square test was conducted to examine the association between place of residence (urban/rural) and malaria prevalence among children aged 6-59 months in Nigeria using nationally representative, survey-weighted data from the 2021 Nigeria Malaria Indicator Survey (MIS) (DHS Program; <em>n</em> = 10,655). <strong>The weighted prevalence of malaria positivity was substantially higher among children residing in rural areas (26.7%, 95% CI [24.4%, 29.1%]) than among those living in urban areas (10.5%, 95% CI [8.6%, 12.8%]) (Rao–Scott adjusted F(1, 491) = 84.72, <em>p</em> &lt; 0.001).</strong> The non-overplapping confidence intervals further confrim this difference is unlikely to be due to chance. This corresponds to a <strong>prevalence ratio</strong> of approximately <strong>2.5</strong>, indicating that children living in rural areas were about <strong>2.5</strong> times as likely to test positive for malaria as those living in urban areas. These findings demonstrate a statistically significant and programmatically meaningful association between place of residence and malaria positivity in Nigeria, reinforcing the need for continued prioritization of rural-focused malaria control interventions (ITN -Insecticide Treated Nets -distributions, IRS -Indoor Residual Spraying, SMC- Seasonal Malaria Chemoprevention) within Nigeria’s National Malaria Elimination Programme.</p>
</section>
<section id="public-health-significance" class="level2">
<h2 class="anchored" data-anchor-id="public-health-significance">8. Public Health Significance</h2>
<p>The observed urban–rural disparity in malaria prevalence among children aged 6-59 months in Nigeria underscores the importance of place of residence as a key public health consideration in malaria control. The higher prevalence observed in rural areas suggests that malaria prevention programmes, including vector control, prompt diagnosis and treatment, seasonal malaria chemoprevention where appropriate, and community health education, should continue to prioritize rural populations. These findings provide evidence to inform policy decisions regarding the equitable distribution of malaria control resources and the strengthening of interventions in areas with the greatest disease burden.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">9. References</h2>
<ul>
<li>National Malaria Elimination Programme (NMEP) [Nigeria], National Population Commission (NPC) [Nigeria], and ICF. (2022). <em>Nigeria Malaria Indicator Survey 2021 Final Report</em>. Abuja, Nigeria, and Rockville, Maryland, USA: NMEP, NPC, and ICF.</li>
</ul>
<!-- -->
<ul>
<li>World Health Organization. (2024). <em>World Malaria Report 2024</em>. Geneva: World Health Organization.</li>
</ul>
<!-- -->
<ul>
<li>The DHS Program. <em>Demographic and Health Surveys Methodology</em>. ICF International.</li>
</ul>
</section>
<section id="explanation-on-weighted-sampling-estimates-strata-clusters" class="level2">
<h2 class="anchored" data-anchor-id="explanation-on-weighted-sampling-estimates-strata-clusters"><strong>Explanation on Weighted Sampling Estimates, Strata &amp; Clusters</strong></h2>
<p><strong>Sampling Weights</strong></p>
<p>DHS surveys use a <strong>stratified, multi-stage cluster sampling design</strong> (<code>hv005</code>) — not a simple random sample of the whole country. In practice, this means certain states, urban/rural areas, or population subgroups may be <strong>deliberately oversampled or undersampled</strong> relative to their true share of the national population (i.e., different population subgroups are sampled at different rates). This is done intentionally, often to ensure smaller states or subgroups have enough sample size to produce statistically reliable prevalence estimates on their own — but it means the <em>raw</em> survey sample doesn’t proportionally represent Nigeria’s actual population composition.</p>
<section id="strata-ensuring-representation-across-key-subgroups" class="level4">
<h4 class="anchored" data-anchor-id="strata-ensuring-representation-across-key-subgroups">Strata — ensuring representation across key subgroups</h4>
<p>Before sampling begins, DHS divides the country into <strong>strata</strong> — typically each state crossed with urban/rural status (which is why the <code>hv023</code> variable had 76 categories: roughly 37 states × urban/rural). Within each stratum, DHS deliberately draws its own independent sample. This guarantees that <strong>every state and every urban/rural combination is represented</strong> in the final data, rather than leaving it to chance (a pure random sample of Nigeria could, by bad luck, end up with very few respondents from a small state — stratification prevents that).</p>
</section>
<section id="clusters-accounting-for-the-fact-that-neighbors-are-more-alike-than-strangers" class="level4">
<h4 class="anchored" data-anchor-id="clusters-accounting-for-the-fact-that-neighbors-are-more-alike-than-strangers">Clusters — accounting for the fact that neighbors are more alike than strangers</h4>
<p>DHS doesn’t randomly select individual households scattered across the entire country — that would be logistically impossible. Instead, it randomly selects <strong>clusters</strong> (usually villages or enumeration areas — your <code>hv021</code>/<code>cluster</code> variable, with 567 of them in your data), then samples multiple households <em>within</em> each selected cluster.</p>
</section>
</section>
<section id="skills-demonstrated" class="level2">
<h2 class="anchored" data-anchor-id="skills-demonstrated"><strong>Skills Demonstrated</strong></h2>
<ul>
<li><p>Working with <strong>real, nationally representative Demographic and Health Survey (DHS) microdata</strong></p></li>
<li><p>Identifying, selecting, and <strong>recoding labelled survey variables</strong></p></li>
<li><p>Conducting <strong>categorical data analysis</strong> using contingency tables</p></li>
<li><p>Performing the <strong>Rao-Scott adjusted chi-square test</strong></p></li>
<li><p>Understanding and applying <strong>complex survey design concepts</strong>, including sampling weights</p></li>
<li><p>Explaining why <strong>weighted estimates</strong> provide more accurate national prevalence estimates than unweighted analyses</p></li>
<li><p>Distinguishing <strong>statistical significance</strong> from <strong>public health (programmatic) significance</strong></p></li>
<li><p>Translating statistical findings into <strong>evidence-based public health recommendations</strong></p></li>
</ul>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>